### PR TITLE
[WIP] Add local subxt-client implementation

### LINKED ISSUE #69: Cannot compile spacewalk client
When building the spacewalk client on the current main branch triggers the following error
```
error: failed to select a version for `parity-util-mem`.
    ... required by package `sp-core v5.0.0 (https://github.com/paritytech/substrate?branch=polkadot-v0.9.17#22d40c76)`
    ... which satisfies git dependency `sp-core` (locked to 5.0.0) of package `subxt v0.16.0 (https://github.com/interlay/subxt?rev=1193d94206a669c59cc5dd89486fecfa82ca584a#1193d942)`
    ... which satisfies git dependency `subxt` (locked to 0.16.0) of package `runtime v1.1.0 (/home/marcel/Documents/Work/spacewalk/clients/runtime)`
    ... which satisfies path dependency `runtime` (locked to 1.1.0) of package `service v1.1.0 (/home/marcel/Documents/Work/spacewalk/clients/service)`
    ... which satisfies path dependency `service` (locked to 1.1.0) of package `vault v0.0.1 (/home/marcel/Documents/Work/spacewalk/clients/vault)`
versions that meet the requirements `^0.10.2` are: 0.10.2

the package `parity-util-mem` links to the native library `parity-util-mem-ban-duplicates`, but it conflicts with a previous package which links to `parity-util-mem-ban-duplicates` as well:
package `parity-util-mem v0.11.0`
    ... which satisfies dependency `parity-util-mem = "^0.11.0"` of package `sp-core v6.0.0 (https://github.com/paritytech/substrate?branch=polkadot-v0.9.18#fc3fd073)`
    ... which satisfies git dependency `sp-core` of package `frame-executive v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v0.9.18#fc3fd073)`
    ... which satisfies git dependency `frame-executive` of package `spacewalk-runtime-standalone v1.2.0 (/home/marcel/Documents/Work/spacewalk/testchain/runtime)`
    ... which satisfies path dependency `spacewalk-runtime` (locked to 1.2.0) of package `runtime v1.1.0 (/home/marcel/Documents/Work/spacewalk/clients/runtime)`
    ... which satisfies path dependency `runtime` (locked to 1.1.0) of package `service v1.1.0 (/home/marcel/Documents/Work/spacewalk/clients/service)`
    ... which satisfies path dependency `service` (locked to 1.1.0) of package `vault v0.0.1 (/home/marcel/Documents/Work/spacewalk/clients/vault)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='parity-util-mem' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `parity-util-mem` which could resolve this conflict
```
This error was likely introduced by #60 since the latest commit that compiles without issues is 1f4cb55. Apparently updating the dependencies to `polkadot-v0.9.18` introduced a version conflict.

### PR DESCRIPTION
**Pull request by ebma**
The [polkadot-v0.9.18 version of interlays subxt fork ](https://github.com/interlay/subxt/tree/polkadot-v0.9.18) does not have a subxt-client implementation anymore. I noticed that in the latest interbtc-clients implementation they use a local implementation for that so I copied that to our clients as well.

Closes #69.

### CODE REVIEW

**Comment by gonzamontiel** [comment]
Oh okay, this is some weird news. Can this be already reviewed?

**Comment by ebma** [comment]
Not yet, there now is a new error when compiling:
```
  error[E0277]: the trait bound `H256: TypeInfo` is not satisfied
     --> /home/marcel/.cargo/git/checkouts/substrate-7e08433d4c370a21/fc3fd07/primitives/runtime/src/traits.rs:511:16
      |
  511 |     type Output = sp_core::H256;
      |                   ^^^^^^^^^^^^^ the trait `TypeInfo` is not implemented for `H256`
      |
      = help: the following other types implement trait `TypeInfo`:
                &T
                &mut T
                ()
                (A, B)
                (A, B, C)
                (A, B, C, D)
                (A, B, C, D, E)
                (A, B, C, D, E, F)
              and 97 others
  note: required by a bound in `traits::Hash::Output`
```

**Comment by xiuxiu62** [comment]
I was pretty lost trying to solve this on friday.  In sp_core 0.9.18, H256 derives TypeInfo: 
```rs
construct_fixed_hash! {
    // Fixed-size uninterpreted hash type with 32 bytes (256 bits) size.
    #[cfg_attr(feature = "scale-info", derive(TypeInfo))]
    pub struct H256(32);
}
That macro applies the meta attributes properly and I'm at loss for where to look.

**Comment by gonzamontiel** [comment]
So the vault client is compiling now, if you run 
`cargo run --bin vault --features standalone-metadata -- --keyring alice --stellar-vault-secret-key <vault-secret>
`
it should work fine.
Tests are still broken though, so `cargo test` will still output some errors. This is because we don't have a working version of the whole setup. This will come after this is merged.

**Review by gonzamontiel — APPROVED** [review]
`cargo run` works. lets merge this.
